/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova'
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request'
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes'
        }
      },
      {
        name: 'alova_user',
        path: '/alova/user',
        component: 'view.alova_user',
        meta: {
          title: 'alova_user',
          i18nKey: 'route.alova_user'
        }
      }
    ]
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      i18nKey: 'route.audit'
    },
    children: [
      {
        name: 'audit_login',
        path: '/audit/login',
        meta: {
          title: 'audit_login',
          i18nKey: 'route.audit_login'
        },
        children: [
          {
            name: 'audit_login_logs',
            path: '/audit/login/logs',
            component: 'view.audit_login_logs',
            meta: {
              title: 'audit_login_logs',
              i18nKey: 'route.audit_login_logs'
            }
          }
        ]
      },
      {
        name: 'audit_operation',
        path: '/audit/operation',
        meta: {
          title: 'audit_operation',
          i18nKey: 'route.audit_operation'
        },
        children: [
          {
            name: 'audit_operation_logs',
            path: '/audit/operation/logs',
            component: 'view.audit_operation_logs',
            meta: {
              title: 'audit_operation_logs',
              i18nKey: 'route.audit_operation_logs'
            }
          }
        ]
      },
      {
        name: 'audit_system',
        path: '/audit/system',
        meta: {
          title: 'audit_system',
          i18nKey: 'route.audit_system'
        },
        children: [
          {
            name: 'audit_system_events',
            path: '/audit/system/events',
            component: 'view.audit_system_events',
            meta: {
              title: 'audit_system_events',
              i18nKey: 'route.audit_system_events'
            }
          }
        ]
      }
    ]
  },
  {
    name: 'cmdb',
    path: '/cmdb',
    component: 'layout.base',
    meta: {
      title: 'cmdb',
      i18nKey: 'route.cmdb'
    },
    children: [
      {
        name: 'cmdb_access',
        path: '/cmdb/access',
        meta: {
          title: 'cmdb_access',
          i18nKey: 'route.cmdb_access'
        },
        children: [
          {
            name: 'cmdb_access_credentials',
            path: '/cmdb/access/credentials',
            component: 'view.cmdb_access_credentials',
            meta: {
              title: 'cmdb_access_credentials',
              i18nKey: 'route.cmdb_access_credentials'
            }
          },
          {
            name: 'cmdb_access_policies',
            path: '/cmdb/access/policies',
            component: 'view.cmdb_access_policies',
            meta: {
              title: 'cmdb_access_policies',
              i18nKey: 'route.cmdb_access_policies'
            }
          }
        ]
      },
      {
        name: 'cmdb_audit',
        path: '/cmdb/audit',
        meta: {
          title: 'cmdb_audit',
          i18nKey: 'route.cmdb_audit'
        },
        children: [
          {
            name: 'cmdb_audit_commands',
            path: '/cmdb/audit/commands',
            component: 'view.cmdb_audit_commands',
            meta: {
              title: 'cmdb_audit_commands',
              i18nKey: 'route.cmdb_audit_commands'
            }
          },
          {
            name: 'cmdb_audit_online',
            path: '/cmdb/audit/online',
            component: 'view.cmdb_audit_online',
            meta: {
              title: 'cmdb_audit_online',
              i18nKey: 'route.cmdb_audit_online'
            }
          },
          {
            name: 'cmdb_audit_sessions',
            path: '/cmdb/audit/sessions',
            component: 'view.cmdb_audit_sessions',
            meta: {
              title: 'cmdb_audit_sessions',
              i18nKey: 'route.cmdb_audit_sessions'
            }
          }
        ]
      },
      {
        name: 'cmdb_business',
        path: '/cmdb/business',
        component: 'view.cmdb_business',
        meta: {
          title: 'cmdb_business',
          i18nKey: 'route.cmdb_business'
        }
      },
      {
        name: 'cmdb_changes',
        path: '/cmdb/changes',
        component: 'view.cmdb_changes',
        meta: {
          title: 'cmdb_changes',
          i18nKey: 'route.cmdb_changes'
        }
      },
      {
        name: 'cmdb_commands',
        path: '/cmdb/commands',
        component: 'view.cmdb_commands',
        meta: {
          title: 'cmdb_commands',
          i18nKey: 'route.cmdb_commands'
        }
      },
      {
        name: 'cmdb_config',
        path: '/cmdb/config',
        meta: {
          title: 'cmdb_config',
          i18nKey: 'route.cmdb_config'
        },
        children: [
          {
            name: 'cmdb_config_agents',
            path: '/cmdb/config/agents',
            component: 'view.cmdb_config_agents',
            meta: {
              title: 'cmdb_config_agents',
              i18nKey: 'route.cmdb_config_agents'
            }
          },
          {
            name: 'cmdb_config_business',
            path: '/cmdb/config/business',
            component: 'view.cmdb_config_business',
            meta: {
              title: 'cmdb_config_business',
              i18nKey: 'route.cmdb_config_business'
            }
          },
          {
            name: 'cmdb_config_rooms',
            path: '/cmdb/config/rooms',
            component: 'view.cmdb_config_rooms',
            meta: {
              title: 'cmdb_config_rooms',
              i18nKey: 'route.cmdb_config_rooms'
            }
          },
          {
            name: 'cmdb_config_tags',
            path: '/cmdb/config/tags',
            component: 'view.cmdb_config_tags',
            meta: {
              title: 'cmdb_config_tags',
              i18nKey: 'route.cmdb_config_tags'
            }
          }
        ]
      },
      {
        name: 'cmdb_dashboard',
        path: '/cmdb/dashboard',
        component: 'view.cmdb_dashboard',
        meta: {
          title: 'cmdb_dashboard',
          i18nKey: 'route.cmdb_dashboard'
        }
      },
      {
        name: 'cmdb_rooms',
        path: '/cmdb/rooms',
        component: 'view.cmdb_rooms',
        meta: {
          title: 'cmdb_rooms',
          i18nKey: 'route.cmdb_rooms'
        }
      },
      {
        name: 'cmdb_server',
        path: '/cmdb/server',
        meta: {
          title: 'cmdb_server',
          i18nKey: 'route.cmdb_server'
        },
        children: [
          {
            name: 'cmdb_server_detail',
            path: '/cmdb/server/detail',
            component: 'view.cmdb_server_detail',
            meta: {
              title: 'cmdb_server_detail',
              i18nKey: 'route.cmdb_server_detail'
            }
          }
        ]
      },
      {
        name: 'cmdb_servers',
        path: '/cmdb/servers',
        component: 'view.cmdb_servers',
        meta: {
          title: 'cmdb_servers',
          i18nKey: 'route.cmdb_servers'
        }
      },
      {
        name: 'cmdb_sessions',
        path: '/cmdb/sessions',
        component: 'view.cmdb_sessions',
        meta: {
          title: 'cmdb_sessions',
          i18nKey: 'route.cmdb_sessions'
        }
      },
      {
        name: 'cmdb_ssh',
        path: '/cmdb/ssh',
        meta: {
          title: 'cmdb_ssh',
          i18nKey: 'route.cmdb_ssh'
        },
        children: [
          {
            name: 'cmdb_ssh_credentials',
            path: '/cmdb/ssh/credentials',
            component: 'view.cmdb_ssh_credentials',
            meta: {
              title: 'cmdb_ssh_credentials',
              i18nKey: 'route.cmdb_ssh_credentials'
            }
          }
        ]
      },
      {
        name: 'cmdb_tags',
        path: '/cmdb/tags',
        component: 'view.cmdb_tags',
        meta: {
          title: 'cmdb_tags',
          i18nKey: 'route.cmdb_tags'
        }
      },
      {
        name: 'cmdb_terminal',
        path: '/cmdb/terminal',
        component: 'view.cmdb_terminal',
        meta: {
          title: 'cmdb_terminal',
          i18nKey: 'route.cmdb_terminal'
        },
        children: [
          {
            name: 'cmdb_terminal_workbench',
            path: '/cmdb/terminal/workbench',
            component: 'view.cmdb_terminal_workbench',
            meta: {
              title: 'cmdb_terminal_workbench',
              i18nKey: 'route.cmdb_terminal_workbench',
              layout: false
            }
          }
        ]
      }
    ]
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function'
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request'
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab'
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      roles: ['超级管理员', 'R_ADMIN', 'R_USER']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          roles: ['超级管理员', 'R_ADMIN', 'R_USER']
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          roles: ['超级管理员', 'R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          roles: ['超级管理员', 'R_ADMIN', 'R_USER']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'monitoring',
    path: '/monitoring',
    component: 'layout.base',
    meta: {
      title: 'monitoring',
      i18nKey: 'route.monitoring'
    },
    children: [
      {
        name: 'monitoring_alerts',
        path: '/monitoring/alerts',
        component: 'view.monitoring_alerts',
        meta: {
          title: 'monitoring_alerts',
          i18nKey: 'route.monitoring_alerts'
        }
      },
      {
        name: 'monitoring_overview',
        path: '/monitoring/overview',
        component: 'view.monitoring_overview',
        meta: {
          title: 'monitoring_overview',
          i18nKey: 'route.monitoring_overview'
        }
      },
      {
        name: 'monitoring_reports',
        path: '/monitoring/reports',
        component: 'view.monitoring_reports',
        meta: {
          title: 'monitoring_reports',
          i18nKey: 'route.monitoring_reports'
        }
      },
      {
        name: 'monitoring_servers',
        path: '/monitoring/servers',
        component: 'view.monitoring_servers',
        meta: {
          title: 'monitoring_servers',
          i18nKey: 'route.monitoring_servers'
        }
      },
      {
        name: 'monitoring_servers-detail',
        path: '/monitoring/servers-detail',
        component: 'view.monitoring_servers-detail',
        meta: {
          title: 'monitoring_servers-detail',
          i18nKey: 'route.monitoring_servers-detail'
        }
      },
      {
        name: 'monitoring_settings',
        path: '/monitoring/settings',
        component: 'view.monitoring_settings',
        meta: {
          title: 'monitoring_settings',
          i18nKey: 'route.monitoring_settings'
        }
      },
      {
        name: 'monitoring_trends',
        path: '/monitoring/trends',
        component: 'view.monitoring_trends',
        meta: {
          title: 'monitoring_trends',
          i18nKey: 'route.monitoring_trends'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu'
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first'
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second'
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: 'plugin',
      i18nKey: 'route.plugin'
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode'
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts'
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv'
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts'
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel'
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt'
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx'
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable'
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf'
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper'
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables'
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable'
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog',
      order: 10
    },
    children: [
      {
        name: 'system_attributes',
        path: '/system/attributes',
        component: 'view.system_attributes',
        meta: {
          title: 'system_attributes',
          i18nKey: 'route.system_attributes',
          icon: 'mdi:format-list-bulleted',
          order: 1
        }
      }
    ]
  },
  {
    name: 'terminal',
    path: '/terminal',
    component: 'layout.base',
    meta: {
      title: 'terminal',
      i18nKey: 'route.terminal',
      icon: 'mdi:console',
      order: 4
    },
    children: [
      {
        name: 'terminal_workbench',
        path: '/terminal/workbench',
        component: 'view.terminal_workbench',
        meta: {
          title: 'terminal_workbench',
          i18nKey: 'route.terminal_workbench',
          layout: false
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  }
];
