/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.base$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.base$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.base$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true
    }
  },
  {
    name: 'about',
    path: '/about',
    component: 'layout.base$view.about',
    meta: {
      title: 'about',
      i18nKey: 'route.about'
    }
  },
  {
    name: 'alova',
    path: '/alova',
    component: 'layout.base',
    meta: {
      title: 'alova',
      i18nKey: 'route.alova'
    },
    children: [
      {
        name: 'alova_request',
        path: '/alova/request',
        component: 'view.alova_request',
        meta: {
          title: 'alova_request',
          i18nKey: 'route.alova_request'
        }
      },
      {
        name: 'alova_scenes',
        path: '/alova/scenes',
        component: 'view.alova_scenes',
        meta: {
          title: 'alova_scenes',
          i18nKey: 'route.alova_scenes'
        }
      },
      {
        name: 'alova_user',
        path: '/alova/user',
        component: 'view.alova_user',
        meta: {
          title: 'alova_user',
          i18nKey: 'route.alova_user'
        }
      }
    ]
  },
  {
    name: 'audit',
    path: '/audit',
    component: 'layout.base',
    meta: {
      title: 'audit',
      i18nKey: 'route.audit'
    },
    children: [
      {
        name: 'audit_login',
        path: '/audit/login',
        component: 'view.audit_login',
        meta: {
          title: 'audit_login',
          i18nKey: 'route.audit_login'
        }
      },
      {
        name: 'audit_operation',
        path: '/audit/operation',
        component: 'view.audit_operation',
        meta: {
          title: 'audit_operation',
          i18nKey: 'route.audit_operation'
        }
      },
      {
        name: 'audit_system',
        path: '/audit/system',
        component: 'view.audit_system',
        meta: {
          title: 'audit_system',
          i18nKey: 'route.audit_system'
        }
      }
    ]
  },
  {
    name: 'auth',
    path: '/auth',
    component: 'layout.base',
    meta: {
      title: 'auth',
      i18nKey: 'route.auth'
    },
    children: [
      {
        name: 'auth_applications',
        path: '/auth/applications',
        component: 'view.auth_applications',
        meta: {
          title: 'auth_applications',
          i18nKey: 'route.auth_applications'
        }
      },
      {
        name: 'auth_operationlogs',
        path: '/auth/operationlogs',
        component: 'view.auth_operationlogs',
        meta: {
          title: 'auth_operationlogs',
          i18nKey: 'route.auth_operationlogs'
        }
      },
      {
        name: 'auth_rolebindings',
        path: '/auth/rolebindings',
        component: 'view.auth_rolebindings',
        meta: {
          title: 'auth_rolebindings',
          i18nKey: 'route.auth_rolebindings'
        }
      },
      {
        name: 'auth_roles',
        path: '/auth/roles',
        component: 'view.auth_roles',
        meta: {
          title: 'auth_roles',
          i18nKey: 'route.auth_roles'
        }
      },
      {
        name: 'auth_user-identities',
        path: '/auth/user-identities',
        component: 'view.auth_user-identities',
        meta: {
          title: 'auth_user-identities',
          i18nKey: 'route.auth_user-identities'
        }
      },
      {
        name: 'auth_user-permissions',
        path: '/auth/user-permissions',
        component: 'view.auth_user-permissions',
        meta: {
          title: 'auth_user-permissions',
          i18nKey: 'route.auth_user-permissions'
        }
      },
      {
        name: 'auth_userauthorization',
        path: '/auth/userauthorization',
        component: 'view.auth_userauthorization',
        meta: {
          title: 'auth_userauthorization',
          i18nKey: 'route.auth_userauthorization'
        }
      },
      {
        name: 'auth_users',
        path: '/auth/users',
        component: 'view.auth_users',
        meta: {
          title: 'auth_users',
          i18nKey: 'route.auth_users'
        }
      }
    ]
  },
  {
    name: 'cmdb',
    path: '/cmdb',
    component: 'layout.base',
    meta: {
      title: 'cmdb',
      i18nKey: 'route.cmdb'
    },
    children: [
      {
        name: 'cmdb_audit',
        path: '/cmdb/audit',
        meta: {
          title: 'cmdb_audit',
          i18nKey: 'route.cmdb_audit'
        },
        children: [
          {
            name: 'cmdb_audit_changes',
            path: '/cmdb/audit/changes',
            component: 'view.cmdb_audit_changes',
            meta: {
              title: 'cmdb_audit_changes',
              i18nKey: 'route.cmdb_audit_changes'
            }
          },
          {
            name: 'cmdb_audit_command',
            path: '/cmdb/audit/command',
            meta: {
              title: 'cmdb_audit_command',
              i18nKey: 'route.cmdb_audit_command'
            },
            children: [
              {
                name: 'cmdb_audit_command_history',
                path: '/cmdb/audit/command/history',
                component: 'view.cmdb_audit_command_history',
                meta: {
                  title: 'cmdb_audit_command_history',
                  i18nKey: 'route.cmdb_audit_command_history'
                }
              }
            ]
          },
          {
            name: 'cmdb_audit_commands',
            path: '/cmdb/audit/commands',
            component: 'view.cmdb_audit_commands',
            meta: {
              title: 'cmdb_audit_commands',
              i18nKey: 'route.cmdb_audit_commands'
            }
          },
          {
            name: 'cmdb_audit_online',
            path: '/cmdb/audit/online',
            component: 'view.cmdb_audit_online',
            meta: {
              title: 'cmdb_audit_online',
              i18nKey: 'route.cmdb_audit_online'
            }
          },
          {
            name: 'cmdb_audit_sessions',
            path: '/cmdb/audit/sessions',
            component: 'view.cmdb_audit_sessions',
            meta: {
              title: 'cmdb_audit_sessions',
              i18nKey: 'route.cmdb_audit_sessions'
            }
          }
        ]
      },
      {
        name: 'cmdb_business',
        path: '/cmdb/business',
        component: 'view.cmdb_business',
        meta: {
          title: 'cmdb_business',
          i18nKey: 'route.cmdb_business'
        }
      },
      {
        name: 'cmdb_config',
        path: '/cmdb/config',
        meta: {
          title: 'cmdb_config',
          i18nKey: 'route.cmdb_config'
        },
        children: [
          {
            name: 'cmdb_config_agents',
            path: '/cmdb/config/agents',
            component: 'view.cmdb_config_agents',
            meta: {
              title: 'cmdb_config_agents',
              i18nKey: 'route.cmdb_config_agents'
            }
          },
          {
            name: 'cmdb_config_business',
            path: '/cmdb/config/business',
            component: 'view.cmdb_config_business',
            meta: {
              title: 'cmdb_config_business',
              i18nKey: 'route.cmdb_config_business'
            }
          },
          {
            name: 'cmdb_config_rooms',
            path: '/cmdb/config/rooms',
            component: 'view.cmdb_config_rooms',
            meta: {
              title: 'cmdb_config_rooms',
              i18nKey: 'route.cmdb_config_rooms'
            }
          },
          {
            name: 'cmdb_config_tags',
            path: '/cmdb/config/tags',
            component: 'view.cmdb_config_tags',
            meta: {
              title: 'cmdb_config_tags',
              i18nKey: 'route.cmdb_config_tags'
            }
          }
        ]
      },
      {
        name: 'cmdb_credentials',
        path: '/cmdb/credentials',
        meta: {
          title: 'cmdb_credentials',
          i18nKey: 'route.cmdb_credentials'
        },
        children: [
          {
            name: 'cmdb_credentials_access',
            path: '/cmdb/credentials/access',
            component: 'view.cmdb_credentials_access',
            meta: {
              title: 'cmdb_credentials_access',
              i18nKey: 'route.cmdb_credentials_access'
            }
          },
          {
            name: 'cmdb_credentials_ssh',
            path: '/cmdb/credentials/ssh',
            component: 'view.cmdb_credentials_ssh',
            meta: {
              title: 'cmdb_credentials_ssh',
              i18nKey: 'route.cmdb_credentials_ssh'
            }
          }
        ]
      },
      {
        name: 'cmdb_dashboard',
        path: '/cmdb/dashboard',
        component: 'view.cmdb_dashboard',
        meta: {
          title: 'cmdb_dashboard',
          i18nKey: 'route.cmdb_dashboard'
        }
      },
      {
        name: 'cmdb_policies',
        path: '/cmdb/policies',
        component: 'view.cmdb_policies',
        meta: {
          title: 'cmdb_policies',
          i18nKey: 'route.cmdb_policies'
        }
      },
      {
        name: 'cmdb_rooms',
        path: '/cmdb/rooms',
        component: 'view.cmdb_rooms',
        meta: {
          title: 'cmdb_rooms',
          i18nKey: 'route.cmdb_rooms'
        }
      },
      {
        name: 'cmdb_server',
        path: '/cmdb/server',
        component: 'view.cmdb_server',
        meta: {
          title: 'cmdb_server',
          i18nKey: 'route.cmdb_server'
        }
      },
      {
        name: 'cmdb_servers',
        path: '/cmdb/servers',
        component: 'view.cmdb_servers',
        meta: {
          title: 'cmdb_servers',
          i18nKey: 'route.cmdb_servers'
        }
      },
      {
        name: 'cmdb_tags',
        path: '/cmdb/tags',
        component: 'view.cmdb_tags',
        meta: {
          title: 'cmdb_tags',
          i18nKey: 'route.cmdb_tags'
        }
      }
    ]
  },
  {
    name: 'demo-route',
    path: '/demo-route',
    component: 'layout.base',
    meta: {
      title: 'demo-route',
      i18nKey: 'route.demo-route'
    },
    children: [
      {
        name: 'demo-route_child',
        path: '/demo-route/child/:id',
        component: 'view.demo-route_child',
        meta: {
          title: 'demo-route_child',
          i18nKey: 'route.demo-route_child'
        }
      }
    ]
  },
  {
    name: 'design-system-demo',
    path: '/design-system-demo',
    component: 'layout.base$view.design-system-demo',
    meta: {
      title: 'design-system-demo',
      i18nKey: 'route.design-system-demo'
    }
  },
  {
    name: 'function',
    path: '/function',
    component: 'layout.base',
    meta: {
      title: 'function',
      i18nKey: 'route.function'
    },
    children: [
      {
        name: 'function_hide-child',
        path: '/function/hide-child',
        meta: {
          title: 'function_hide-child',
          i18nKey: 'route.function_hide-child'
        },
        children: [
          {
            name: 'function_hide-child_one',
            path: '/function/hide-child/one',
            component: 'view.function_hide-child_one',
            meta: {
              title: 'function_hide-child_one',
              i18nKey: 'route.function_hide-child_one'
            }
          },
          {
            name: 'function_hide-child_three',
            path: '/function/hide-child/three',
            component: 'view.function_hide-child_three',
            meta: {
              title: 'function_hide-child_three',
              i18nKey: 'route.function_hide-child_three'
            }
          },
          {
            name: 'function_hide-child_two',
            path: '/function/hide-child/two',
            component: 'view.function_hide-child_two',
            meta: {
              title: 'function_hide-child_two',
              i18nKey: 'route.function_hide-child_two'
            }
          }
        ]
      },
      {
        name: 'function_multi-tab',
        path: '/function/multi-tab',
        component: 'view.function_multi-tab',
        meta: {
          title: 'function_multi-tab',
          i18nKey: 'route.function_multi-tab'
        }
      },
      {
        name: 'function_request',
        path: '/function/request',
        component: 'view.function_request',
        meta: {
          title: 'function_request',
          i18nKey: 'route.function_request'
        }
      },
      {
        name: 'function_super-page',
        path: '/function/super-page',
        component: 'view.function_super-page',
        meta: {
          title: 'function_super-page',
          i18nKey: 'route.function_super-page'
        }
      },
      {
        name: 'function_tab',
        path: '/function/tab',
        component: 'view.function_tab',
        meta: {
          title: 'function_tab',
          i18nKey: 'route.function_tab'
        }
      },
      {
        name: 'function_toggle-auth',
        path: '/function/toggle-auth',
        component: 'view.function_toggle-auth',
        meta: {
          title: 'function_toggle-auth',
          i18nKey: 'route.function_toggle-auth'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page'
    }
  },
  {
    name: 'k8s',
    path: '/k8s',
    component: 'layout.base',
    meta: {
      title: 'k8s',
      i18nKey: 'route.k8s'
    },
    children: [
      {
        name: 'k8s_clusters',
        path: '/k8s/clusters',
        component: 'view.k8s_clusters',
        meta: {
          title: 'k8s_clusters',
          i18nKey: 'route.k8s_clusters'
        }
      },
      {
        name: 'k8s_config',
        path: '/k8s/config',
        component: 'view.k8s_config',
        meta: {
          title: 'k8s_config',
          i18nKey: 'route.k8s_config'
        }
      },
      {
        name: 'k8s_diagnostic',
        path: '/k8s/diagnostic',
        component: 'view.k8s_diagnostic',
        meta: {
          title: 'k8s_diagnostic',
          i18nKey: 'route.k8s_diagnostic'
        }
      },
      {
        name: 'k8s_network',
        path: '/k8s/network',
        component: 'view.k8s_network',
        meta: {
          title: 'k8s_network',
          i18nKey: 'route.k8s_network'
        }
      },
      {
        name: 'k8s_resources',
        path: '/k8s/resources',
        meta: {
          title: 'k8s_resources',
          i18nKey: 'route.k8s_resources'
        },
        children: [
          {
            name: 'k8s_resources_configmaps',
            path: '/k8s/resources/configmaps',
            component: 'view.k8s_resources_configmaps',
            meta: {
              title: 'k8s_resources_configmaps',
              i18nKey: 'route.k8s_resources_configmaps'
            }
          },
          {
            name: 'k8s_resources_deployments',
            path: '/k8s/resources/deployments',
            component: 'view.k8s_resources_deployments',
            meta: {
              title: 'k8s_resources_deployments',
              i18nKey: 'route.k8s_resources_deployments'
            }
          },
          {
            name: 'k8s_resources_pods',
            path: '/k8s/resources/pods',
            component: 'view.k8s_resources_pods',
            meta: {
              title: 'k8s_resources_pods',
              i18nKey: 'route.k8s_resources_pods'
            }
          },
          {
            name: 'k8s_resources_secrets',
            path: '/k8s/resources/secrets',
            component: 'view.k8s_resources_secrets',
            meta: {
              title: 'k8s_resources_secrets',
              i18nKey: 'route.k8s_resources_secrets'
            }
          },
          {
            name: 'k8s_resources_services',
            path: '/k8s/resources/services',
            component: 'view.k8s_resources_services',
            meta: {
              title: 'k8s_resources_services',
              i18nKey: 'route.k8s_resources_services'
            }
          }
        ]
      },
      {
        name: 'k8s_terminal',
        path: '/k8s/terminal',
        component: 'view.k8s_terminal',
        meta: {
          title: 'k8s_terminal',
          i18nKey: 'route.k8s_terminal'
        }
      },
      {
        name: 'k8s_workloads',
        path: '/k8s/workloads',
        component: 'view.k8s_workloads',
        meta: {
          title: 'k8s_workloads',
          i18nKey: 'route.k8s_workloads'
        }
      }
    ]
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.base$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true
    }
  },
  {
    name: 'manage',
    path: '/manage',
    component: 'layout.base',
    meta: {
      title: 'manage',
      i18nKey: 'route.manage',
      roles: ['超级管理员', 'R_ADMIN', 'R_USER']
    },
    children: [
      {
        name: 'manage_menu',
        path: '/manage/menu',
        component: 'view.manage_menu',
        meta: {
          title: 'manage_menu',
          i18nKey: 'route.manage_menu',
          roles: ['超级管理员', 'R_ADMIN', 'R_USER']
        }
      },
      {
        name: 'manage_permission',
        path: '/manage/permission',
        component: 'view.manage_permission',
        meta: {
          title: 'manage_permission',
          i18nKey: 'route.manage_permission'
        }
      },
      {
        name: 'manage_role',
        path: '/manage/role',
        component: 'view.manage_role',
        meta: {
          title: 'manage_role',
          i18nKey: 'route.manage_role',
          roles: ['超级管理员', 'R_SUPER']
        }
      },
      {
        name: 'manage_user',
        path: '/manage/user',
        component: 'view.manage_user',
        meta: {
          title: 'manage_user',
          i18nKey: 'route.manage_user',
          roles: ['超级管理员', 'R_ADMIN', 'R_USER']
        }
      },
      {
        name: 'manage_user-detail',
        path: '/manage/user-detail/:id',
        component: 'view.manage_user-detail',
        meta: {
          title: 'manage_user-detail',
          i18nKey: 'route.manage_user-detail'
        }
      }
    ]
  },
  {
    name: 'monitoring',
    path: '/monitoring',
    component: 'layout.base',
    meta: {
      title: 'monitoring',
      i18nKey: 'route.monitoring'
    },
    children: [
      {
        name: 'monitoring_alerts',
        path: '/monitoring/alerts',
        component: 'view.monitoring_alerts',
        meta: {
          title: 'monitoring_alerts',
          i18nKey: 'route.monitoring_alerts'
        }
      },
      {
        name: 'monitoring_overview',
        path: '/monitoring/overview',
        component: 'view.monitoring_overview',
        meta: {
          title: 'monitoring_overview',
          i18nKey: 'route.monitoring_overview'
        }
      },
      {
        name: 'monitoring_reports',
        path: '/monitoring/reports',
        component: 'view.monitoring_reports',
        meta: {
          title: 'monitoring_reports',
          i18nKey: 'route.monitoring_reports'
        }
      },
      {
        name: 'monitoring_servers',
        path: '/monitoring/servers',
        meta: {
          title: 'monitoring_servers',
          i18nKey: 'route.monitoring_servers'
        },
        children: [
          {
            name: 'monitoring_servers_detail',
            path: '/monitoring/servers/detail',
            component: 'view.monitoring_servers_detail',
            meta: {
              title: 'monitoring_servers_detail',
              i18nKey: 'route.monitoring_servers_detail'
            }
          }
        ]
      },
      {
        name: 'monitoring_settings',
        path: '/monitoring/settings',
        component: 'view.monitoring_settings',
        meta: {
          title: 'monitoring_settings',
          i18nKey: 'route.monitoring_settings'
        }
      },
      {
        name: 'monitoring_trends',
        path: '/monitoring/trends',
        component: 'view.monitoring_trends',
        meta: {
          title: 'monitoring_trends',
          i18nKey: 'route.monitoring_trends'
        }
      }
    ]
  },
  {
    name: 'multi-menu',
    path: '/multi-menu',
    component: 'layout.base',
    meta: {
      title: 'multi-menu',
      i18nKey: 'route.multi-menu'
    },
    children: [
      {
        name: 'multi-menu_first',
        path: '/multi-menu/first',
        meta: {
          title: 'multi-menu_first',
          i18nKey: 'route.multi-menu_first'
        },
        children: [
          {
            name: 'multi-menu_first_child',
            path: '/multi-menu/first/child',
            component: 'view.multi-menu_first_child',
            meta: {
              title: 'multi-menu_first_child',
              i18nKey: 'route.multi-menu_first_child'
            }
          }
        ]
      },
      {
        name: 'multi-menu_second',
        path: '/multi-menu/second',
        meta: {
          title: 'multi-menu_second',
          i18nKey: 'route.multi-menu_second'
        },
        children: [
          {
            name: 'multi-menu_second_child',
            path: '/multi-menu/second/child',
            meta: {
              title: 'multi-menu_second_child',
              i18nKey: 'route.multi-menu_second_child'
            },
            children: [
              {
                name: 'multi-menu_second_child_home',
                path: '/multi-menu/second/child/home',
                component: 'view.multi-menu_second_child_home',
                meta: {
                  title: 'multi-menu_second_child_home',
                  i18nKey: 'route.multi-menu_second_child_home'
                }
              }
            ]
          }
        ]
      }
    ]
  },
  {
    name: 'plugin',
    path: '/plugin',
    component: 'layout.base',
    meta: {
      title: 'plugin',
      i18nKey: 'route.plugin'
    },
    children: [
      {
        name: 'plugin_barcode',
        path: '/plugin/barcode',
        component: 'view.plugin_barcode',
        meta: {
          title: 'plugin_barcode',
          i18nKey: 'route.plugin_barcode'
        }
      },
      {
        name: 'plugin_charts',
        path: '/plugin/charts',
        meta: {
          title: 'plugin_charts',
          i18nKey: 'route.plugin_charts'
        },
        children: [
          {
            name: 'plugin_charts_antv',
            path: '/plugin/charts/antv',
            component: 'view.plugin_charts_antv',
            meta: {
              title: 'plugin_charts_antv',
              i18nKey: 'route.plugin_charts_antv'
            }
          },
          {
            name: 'plugin_charts_echarts',
            path: '/plugin/charts/echarts',
            component: 'view.plugin_charts_echarts',
            meta: {
              title: 'plugin_charts_echarts',
              i18nKey: 'route.plugin_charts_echarts'
            }
          },
          {
            name: 'plugin_charts_vchart',
            path: '/plugin/charts/vchart',
            component: 'view.plugin_charts_vchart',
            meta: {
              title: 'plugin_charts_vchart',
              i18nKey: 'route.plugin_charts_vchart'
            }
          }
        ]
      },
      {
        name: 'plugin_copy',
        path: '/plugin/copy',
        component: 'view.plugin_copy',
        meta: {
          title: 'plugin_copy',
          i18nKey: 'route.plugin_copy'
        }
      },
      {
        name: 'plugin_editor',
        path: '/plugin/editor',
        meta: {
          title: 'plugin_editor',
          i18nKey: 'route.plugin_editor'
        },
        children: [
          {
            name: 'plugin_editor_markdown',
            path: '/plugin/editor/markdown',
            component: 'view.plugin_editor_markdown',
            meta: {
              title: 'plugin_editor_markdown',
              i18nKey: 'route.plugin_editor_markdown'
            }
          },
          {
            name: 'plugin_editor_quill',
            path: '/plugin/editor/quill',
            component: 'view.plugin_editor_quill',
            meta: {
              title: 'plugin_editor_quill',
              i18nKey: 'route.plugin_editor_quill'
            }
          }
        ]
      },
      {
        name: 'plugin_excel',
        path: '/plugin/excel',
        component: 'view.plugin_excel',
        meta: {
          title: 'plugin_excel',
          i18nKey: 'route.plugin_excel'
        }
      },
      {
        name: 'plugin_gantt',
        path: '/plugin/gantt',
        meta: {
          title: 'plugin_gantt',
          i18nKey: 'route.plugin_gantt'
        },
        children: [
          {
            name: 'plugin_gantt_dhtmlx',
            path: '/plugin/gantt/dhtmlx',
            component: 'view.plugin_gantt_dhtmlx',
            meta: {
              title: 'plugin_gantt_dhtmlx',
              i18nKey: 'route.plugin_gantt_dhtmlx'
            }
          },
          {
            name: 'plugin_gantt_vtable',
            path: '/plugin/gantt/vtable',
            component: 'view.plugin_gantt_vtable',
            meta: {
              title: 'plugin_gantt_vtable',
              i18nKey: 'route.plugin_gantt_vtable'
            }
          }
        ]
      },
      {
        name: 'plugin_icon',
        path: '/plugin/icon',
        component: 'view.plugin_icon',
        meta: {
          title: 'plugin_icon',
          i18nKey: 'route.plugin_icon'
        }
      },
      {
        name: 'plugin_map',
        path: '/plugin/map',
        component: 'view.plugin_map',
        meta: {
          title: 'plugin_map',
          i18nKey: 'route.plugin_map'
        }
      },
      {
        name: 'plugin_pdf',
        path: '/plugin/pdf',
        component: 'view.plugin_pdf',
        meta: {
          title: 'plugin_pdf',
          i18nKey: 'route.plugin_pdf'
        }
      },
      {
        name: 'plugin_pinyin',
        path: '/plugin/pinyin',
        component: 'view.plugin_pinyin',
        meta: {
          title: 'plugin_pinyin',
          i18nKey: 'route.plugin_pinyin'
        }
      },
      {
        name: 'plugin_print',
        path: '/plugin/print',
        component: 'view.plugin_print',
        meta: {
          title: 'plugin_print',
          i18nKey: 'route.plugin_print'
        }
      },
      {
        name: 'plugin_swiper',
        path: '/plugin/swiper',
        component: 'view.plugin_swiper',
        meta: {
          title: 'plugin_swiper',
          i18nKey: 'route.plugin_swiper'
        }
      },
      {
        name: 'plugin_tables',
        path: '/plugin/tables',
        meta: {
          title: 'plugin_tables',
          i18nKey: 'route.plugin_tables'
        },
        children: [
          {
            name: 'plugin_tables_vtable',
            path: '/plugin/tables/vtable',
            component: 'view.plugin_tables_vtable',
            meta: {
              title: 'plugin_tables_vtable',
              i18nKey: 'route.plugin_tables_vtable'
            }
          }
        ]
      },
      {
        name: 'plugin_typeit',
        path: '/plugin/typeit',
        component: 'view.plugin_typeit',
        meta: {
          title: 'plugin_typeit',
          i18nKey: 'route.plugin_typeit'
        }
      },
      {
        name: 'plugin_video',
        path: '/plugin/video',
        component: 'view.plugin_video',
        meta: {
          title: 'plugin_video',
          i18nKey: 'route.plugin_video'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system',
      icon: 'mdi:cog',
      order: 10
    },
    children: [
      {
        name: 'system_attributes',
        path: '/system/attributes',
        component: 'view.system_attributes',
        meta: {
          title: 'system_attributes',
          i18nKey: 'route.system_attributes',
          icon: 'mdi:format-list-bulleted',
          order: 1
        }
      }
    ]
  },
  {
    name: 'user-center',
    path: '/user-center',
    component: 'layout.base$view.user-center',
    meta: {
      title: 'user-center',
      i18nKey: 'route.user-center'
    }
  },
  {
    name: 'webterminal',
    path: '/webterminal',
    component: 'layout.base$view.webterminal',
    meta: {
      title: 'webterminal',
      i18nKey: 'route.webterminal'
    }
  }
];
